allmunde:
    adapter: ENC[AES256_GCM,data:rjcm9fH0J4Nt2w==,iv:lKkjxLcf0P0OlK8swvnRS422ULwIyvGzvJLEk8vjubk=,tag:6Nk++7GRXNu4VE2DNI+58A==,type:str]
    database: ENC[AES256_GCM,data:GITrn1O1LnFT11tvX+e64vpJ,iv:SQX63sY1Hv1NQazL/lN2fPcoJImdVO8jkYoFscq4DHI=,tag:jWjMt5ILUeEcb3ujHnCspA==,type:str]
    user: ENC[AES256_GCM,data:cqhiS2oBe7vU,iv:3N5Btn4A/futVkNNhmrN1AFxFl5uDg8Tsq5iOa/wslk=,tag:a7tFFEc7lFeYkOsP9H0DIg==,type:str]
    password: ENC[AES256_GCM,data:dq2QouaXtQUf2AlXIiodraHnAyI5BQ==,iv:sIKLbKmKiMcmGtss8JNIA/S4AdlKD4/atFzggK7auy8=,tag:FspzEPNU58WffQzqtoWIKA==,type:str]
    host: ENC[AES256_GCM,data:c6B5/lwbgfg=,iv:3elGjDUNNX95XyCqwnBIXPuo0F6uHFR0bw4R102f45A=,tag:FA7cOK8sLU4lMFZYNN+IpQ==,type:str]
    pool: ENC[AES256_GCM,data:8A==,iv:eyn/u4sGLRM25LLJlIOUgXAbJVniQIsBsQ5FRUB8Om4=,tag:uYZvJQ7EnYTu1iFB2BxuvA==,type:int]
    timeout: ENC[AES256_GCM,data:ND1q2Q==,iv:5XLVY+3/ZzWSJK6uFJLcmme9XnIDy1Mhhk1P2WjLczk=,tag:nmP6MoZahiHXlSCRl7yp5A==,type:int]
    db_id: ENC[AES256_GCM,data:4Q==,iv:zUk1D7ke5JkTJdBD7y3H3IOfdRjrLLTT8MSCEsv1Wok=,tag:OlWurXmJuLH1Ju7EeL4Qiw==,type:int]
    host_names:
        - ENC[AES256_GCM,data:M/m33l0vZdfsZ4ajMUcGJhFI,iv:K+BgWmVhcFfOat5SxXlXMIcsvK1wkBO+uZ4MEjV9SZU=,tag:Ri5KTjLS5Zw71XxT4fpa4w==,type:str]
        - ENC[AES256_GCM,data:09Mw31EYEjob0OcPx3Ye,iv:esBAn0BvrDrvzciUKf087O0ospCMzSzZ6chiATRkHpg=,tag:h1J6yHXDXuCm1gVTgelHEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age134ua239eacs8dk5lrys5g7wtfa90tv9y9cnzw984wmkwfjaslu7qd9luys
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1R3lUcmNHS2VjVFNPaUJk
            eVEzRy9mK21aUU94eFJQUWU2emhjcTMzbVhFCk9wZCtPUDJBdERLRGFIWVdiSmhC
            Qlgzbis4RzdoSWFsTnBGc1pHdVVFUWsKLS0tIDg0TGtRKy9EUGZIcWlOYjZYdDFk
            UkNIT2xEdzltenlZS0ZlWGlrWWxMZG8KEu8d/uDG0M3EIusp9M5yHqppOqjTcyVN
            44+Wb5UcbaOH0vtCP7aP1csVpMe7KoHAsVo2qjhrPf7KcAB2sjwz5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T22:42:26Z"
    mac: ENC[AES256_GCM,data:wT6H+A95XXsauGgdbyUZX6a8V6EZFVY/0OU4FF7RIYCa5GeySkUGL2OvV33Sk4JPqT0gt5WxLtiODm/r7xZ2gGnfXIZ35Nt/nS4/cji+cri2vzdTjnQmFOM5bLuBM6goVXKlOQL+IWVJIOtvjLDFfpKb/xYmpipbcaDXhmQMuC8=,iv:yJj1SW37z7JRRkO3fOP8kxKq2eQcTyXhXhFP2p8RUVw=,tag:Qhb+SV7AHiYaunoHUwaVWw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
